Adding Create and Delete SubmodelElement API
eclipse-basyx/basyx-java-components pull request #284
Opened 2023-03-03 12:49 UTC by zhangzai123

2023-03-06 08:15 UTC, FrankSchnicke requested changes
There are no tests for the new methods in SubmodelRepository, please add them. Additionally, SubmodelElementList & Entity are not covered by the implementation & tests.

2023-03-06 14:29 UTC, zhangzai123 commented on basyx.http/src/test/java/org/eclipse/digitaltwin/basyx/http/serialization/BaSyxHttpTestUtils.java
> +	private static HttpDelete createDeleteRequestHeader(String url) {
checked

2023-03-06 14:31 UTC, zhangzai123 commented on basyx.submodelrepository-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/SubmodelRepository.java
> +	 * Creates a nested SubmodelElement in a submodelelement collection
checked

2023-03-06 14:32 UTC, zhangzai123 commented on basyx.submodelrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/SubmodelRepositoryApiHTTPController.java
> +
checked

2023-03-06 14:36 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelService.java
> +	 * Create a submodel element in a submodel element collection
checked

2023-03-06 14:36 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelService.java
> +	 *             If the submodel element collection does not exist
checked

2023-03-06 14:37 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelService.java
> +	 *             If the submodel element collection does not exist
checked

2023-03-06 14:37 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/pathParsing/HierarchicalSubmodelElementParser.java
> +	 *            the isShortPath of the SubmodelElement
checked

2023-03-06 14:38 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/pathParsing/HierarchicalSubmodelElementParser.java
> +	 * Check whether the given idShortPath is a simple siDhort or a path of idShorts
checked

2023-03-06 15:16 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/pathParsing/HierarchicalSubmodelElementParser.java
> +		return idShortPath.contains(".");
checked

2023-03-06 15:24 UTC, zhangzai123 commented on basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
> +		if (submodelElementExistAlready(submodelElement, smElements)) {
checked

2023-03-06 15:24 UTC, zhangzai123 commented on basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
> +		if (submodelElementExistAlready(submodelElement, submodelElements)) {
cehcked

2023-03-07 13:24 UTC, zhangzai123 commented on basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
> +	private boolean submodelElementExistAlready(SubmodelElement submodelElement, Collection<SubmodelElement> smElements) {
checked

2023-03-09 09:40 UTC, zhangzai123 commented on basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java
> +		PropertyValue createdValue = (PropertyValue) submodelService.getSubmodelElementValue(idShortPath);
checked

2023-03-09 11:17 UTC, zhangzai123 commented on basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java
> +		createNestedSubmodelElement(submodelService);
checked

2023-03-09 11:17 UTC, zhangzai123 commented on basyx.submodelservice-core/src/test/java/org/eclipse/digitaltwin/basyx/submodelservice/SubmodelServiceSuite.java
> +	public void deleteNestedSubmodelElement() {
checked

2023-03-09 12:43 UTC, zhangzai123 commented on basyx.submodelservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/InMemorySubmodelService.java
> +		SubmodelElementCollection collection = (SubmodelElementCollection) parser.getSubmodelElementFromIdShortPath(idShortPath);
checked

2023-03-09 12:43 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/pathParsing/HierarchicalSubmodelElementParser.java
> +	public boolean isNestedIdShortPath(String idShortPath) {
checked

2023-03-09 12:43 UTC, zhangzai123 commented on basyx.submodelservice-core/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/pathParsing/HierarchicalSubmodelElementParser.java
> +	public String extractDirectParentIdShortOfNestedSubmodelElement(String idShortPath) {
checked

2023-03-09 12:45 UTC, zhangzai123 commented on basyx.submodelrepository-http/src/test/java/org/eclipse/digitaltwin/basyx/submodelrepository/http/TestSubmodelRepositorySubmodelElementsHTTP.java
> +	public void createExistingSubmodelElement() throws IOException {
checked

2023-03-13 09:38 UTC, closed without merging