add support for exterior Updater-configs
eclipse-basyx/basyx-java-components pull request #66
Opened 2022-03-24 02:20 UTC by n14s

Closes #65 

Updater Config files can be read outside from packed jar or Docker Container.
This allows the configuration of the packed application in deployment.

As a demonstration, consider [this docker-compose repo](https://github.com/n14s/prometheus-aas-docker), which uses a route that connects Prometheus to the AAS. 
It incorporates the changes of this PR.

2022-03-24 02:37 UTC, n14s commented
There might be a possible side effect depending on the IDE.
Using Intellij on Ubuntu 18.04, I need to set the working directory in the run configurations to the resource directory, when running the examples.

2022-04-06 10:30 UTC, FrankSchnicke commented
Many thanks for providing this PR. 
The mentioned issue with the IDE also persists for the Eclipse IDE. Is there any possibility for adapting your PR so that it still works without any classpath reconfigurations?

2022-04-08 13:39 UTC, n14s commented
> Many thanks for providing this PR. The mentioned issue with the IDE also persists for the Eclipse IDE. Is there any possibility for adapting your PR so that it still works without any classpath reconfigurations?

ce96 allows for exterior config loading with the previous classpath loading as fallback.

Unfortunatly there remains a problem when loading the jsonata config file (eg. jsonataA.json in the examples) as defined in the jsonatatransformer.json and loaded in the JsonataTransformerConfiguration.

To clarify, there are two locations in the code where config files are loaded. 

One is the general config file loading in FileConfigurationLoader. \
ce96 makes it work for both cases, deployed and in the IDE. 

The other one is the loading of the specific jsonata config that's used in the route, defined in JsonataTransformerConfiguration.
Working with this piece of code is harder since it's just defining the jsonata config in the Camel DSL without allowing for a case distinction, as implemented in ce96 for the general configs.

This is a snippet of the diff between the two options that make it either work in the IDE or deployed: 

```
public String getConnectionURI() { 

-   	String url = "jsonata:" + getQueryPath() + "?inputType=" + getInputType() + "&outputType=" + getOutputType(); 

+       String url = "jsonata:" + "file:./"  + getQueryPath() + "?inputType=" + getInputType() + "&outputType=" + getOutputType(); 

 		return url;
 	    }

```
Do you have an idea how to make a case distinction for the loading of the jsonata config, or an other way to approach the problem?

2022-04-15 15:56 UTC, n14s commented
Fixed the problem by using a case distinction based on the existance of the jsonata config-file as defined in the jsonatatransformer.json: 
- If it finds it, it uses that file. (deployment case) 
- If not, it looks for the file in the classpath. (IDE case) \
\
Tested both cases successfully.

2022-04-19 06:23 UTC, FrankSchnicke requested changes

2022-04-19 06:23 UTC, FrankSchnicke commented on basyx.components/basyx.components.updater/basyx.components.updater.transformer.camel-jsonata/src/main/java/basyx/components/updater/transformer/cameljsonata/configuration/JsonataTransformerConfiguration.java
> +		    System.out.println("Looking for jsonata config as configured in jsonatatransformer.json...");
Would it be possible to replace this println with a logger call?

2022-04-19 06:23 UTC, FrankSchnicke commented on basyx.components/basyx.components.updater/basyx.components.updater.transformer.camel-jsonata/src/main/java/basyx/components/updater/transformer/cameljsonata/configuration/JsonataTransformerConfiguration.java
> +			System.out.println("Couldn't find jsonata config as configured in jsonatatransformer.json. Looking in classpath...");
Would it be possible to replace this println with a logger call?

2022-04-19 06:24 UTC, FrankSchnicke commented
The solution looks great! Would it be possible to address the two small review remarks? Afterwards, I will merge.

2022-04-22 06:05 UTC, n14s commented
No problem!

2022-04-22 06:06 UTC, FrankSchnicke approved these changes

2022-04-22 06:06 UTC, merged