Feature: Add Http-Polling and Prometheus Components
eclipse-basyx/basyx-java-components pull request #70
Opened 2022-03-25 14:05 UTC by n14s

Addresses #34 

This PR contains two new updater components, their example modules and an auxiliary component:
- Http Polling Updater
- Prometheus Updater
- Http-jsonata-aas example
- Prometheus-jsonata-aas example
- Timer (auxiliary component)

With these components, data from Http or Prometheus Endpoints can be integrated into the AAS.
Especially integrating device data via tools like Prometheus is essential for creating digital twins via AAS.

### Technical details:
- Prometheus component is an extension of the HttpPolling component, facilitating the query of metrics
- Route creation in UpdaterRouteBuilder has been extended to support the components
- HttpPolling example works out of the box, Prometheus example requires a basic Prometheus + nodeexporter instance running
- This PR only devolps its full functionality with #66, since its goal is to be deployed, while still being able to be configured.

### Try it out:
The easiest way to try it out is to clone and run [this docker-compose stack](https://github.com/n14s/prometheus-aas-docker).\
It collects metric data and sends it to the AAS using the Prometheus Component.  

The core element of the compose stack is the Prometheus-AAS-Router service, where the Updater with the Prometheus component resides.\
[Check out its repo](https://github.com/n14s/prometheus-aas-router) for more details on how the the underlying Java application works and how the image is built

### Open issue 
#### Camels Http component doesn't fit well into Basyx Updater route scheme:
Routes and route creation works different with camels Http component, as it starts with a timer

`from(timer).to(consumer).to(producer)`

instead of starting with the datasource

`from(consumer).to(producer)`

Therefore, conforming the Updater route scheme provides:\
Datasource = timer \
Datasink[0] = Http/Prometheus \
Datasink[1] = AAS  

This can be explored in the routes.json of the HttpPolling/Prometheus examples or in the demonstration compose stack.

In this PR the workaround results in a working solution, but the Basyx Updater scheme should consider altering its scheme for a cleaner integration of http endpoints.

2022-04-06 11:46 UTC, FrankSchnicke requested changes
Many thanks for this comprehensive PR! Would it be possible to address the single review point?

We will change the UpdaterRouteBuilder in future to support a more consistent configuration.

2022-04-06 11:46 UTC, FrankSchnicke commented on basyx.components/basyx.components.updater/basyx.components.updater.core/src/main/java/basyx/components/updater/core/routebuilder/UpdaterRouteBuilder.java
> +			if (dataSourceEndpoint.startsWith("timer") == true) {
Please remove the "== true"

2022-04-07 11:53 UTC, n14s commented on basyx.components/basyx.components.updater/basyx.components.updater.core/src/main/java/basyx/components/updater/core/routebuilder/UpdaterRouteBuilder.java
> +			if (dataSourceEndpoint.startsWith("timer") == true) {
Will do

2022-04-25 05:59 UTC, n14s commented
Did 536d solve the remark?

2022-04-25 06:01 UTC, FrankSchnicke approved these changes

2022-04-25 06:01 UTC, merged

2022-04-25 06:02 UTC, FrankSchnicke commented
Yes it did - I somehow missed this update. Thank you for pointing out the fix.